### ISSUE TITLE
Margins are limited

### ISSUE THREAD

**Issue by Furezuu** [LGUG2Z/yatta#19]
I would like to have my margins in yatta like 5 or 10 pixels, but low limit of margins is too high. Will it be improved?

**Comment by LGUG2Z** [comment]
For the outer margins (around the entire display), this is currently hard coded (https://github.com/LGUG2Z/yatta/blob/master/yatta/src/desktop.rs#L532).

Maybe this could be dropped to `15` and still look okay, but when dropped further than that, the margins stop changing equally between the vertical and the horizontal axis and it doesn't look great. I've attached an example to show what I mean when this value is reduced even to `5`.

![Screenshot 2021-07-23 122420](https://user-images.githubusercontent.com/13164844/126831537-04a779ca-b3ba-4823-9891-decf07dd6d2a.png)

I have no objections to making the `PADDING` variable modifiable via `yattac` so that this can be set per-user in their configuration (similar to the `yattac.exe gap-size N` option to set the gaps between the windows), however, digging in to how to get the outer margin padding to stay consistent at lower values is not a rabbit hole I'm willing to go down myself.

**Comment by LGUG2Z** [comment]
@Furezuu With the latest commit to the `master` branch, you will be able to specify `yattac.exe padding-size N` in your AHK configuration to set the padding around the screen to the value of your choice. 🎉
